DATADIR = /scratch/sylju
HOMEDIR = $(HOME)
INCDIR = -I$(DATADIR)/include -I$(HOMEDIR)/include -I/usr/include 
LIBDIR = -L$(DATADIR)/lib     -L$(HOMEDIR)/lib     -L/usr/lib
LIBS   = -lfftw3 -lm -lrand -lstdc++ 
BINDIR = $(DATADIR)/bin
EXTENSION = _x64.x

# C++ compiler
CCC= g++

CCOPTS=  -std=c++11 -O3 -DNDEBUG

LINKOPTS =  -O3 

CCFLAGS = $(CCOPTS) $(INCDIR) 






